### ISSUE TITLE
YAML as a string diagram

### ISSUE THREAD

**Issue by colltoaction** [discopy/discopy#211]
I recently discovered this library and the papers behind it and I was blown away. Great work!

---

I know this is ambitious but I want YAML, with its [representation graph](https://yaml.org/spec/1.2.2/#321-representation-graph) and human-friendliness, be the definitive language to write string diagrams for computing.

The DisCoPy Python API is very friendly, and I want to provide an alternative syntax using YAML. 
Abstracting DisCoCat from Python would be beneficial for example to implement the computations in any language that can read YAML (basically every language).

I'm doing some POCs but I haven't yet settled on a semantic. E.g, I know I want to use `mapping`s as parallel composition and `sequences`s as sequential composition.

This NetworkX discussion is also related https://github.com/networkx/networkx/discussions/6808.

Of course I'm happy to go into more details, and thanks for reading!

**Comment by colltoaction** [comment]
some examples from the QNLP tutorial would be

```yaml
- sentence
- qubit
```

```yaml
- egg
- white
- yolk
```

```yaml
name: crack
dom:
  - egg
cod:
  - white
  - yolk
```

**Comment by toumix** [comment]
Using YAML to write string diagrams seems like a promising idea!

> Abstracting DisCoCat from Python would be beneficial for example to implement the computations in any language that can read YAML (basically every language).

I very much agree with this, but I would say that JSON is good enough when it comes to a machine-readable language for diagrams. YAML is interesting because it's also human-readable.

> I want to use mappings as parallel composition

Parallel composition has an order (`f @ g` is not the same as `g @ f`) whereas mappings don't. Also, what would be the keys? 

> sequences as sequential composition

This makes sense!

> some examples from the QNLP tutorial would be

The syntax for boxes makes sense, can you give an example of what composition should look like?

**Comment by toumix** [comment]
One way to make this YAML proposal much more readable than the verbose JSON we have at the moment would be to have a syntax for signatures (i.e. sets of boxes with their name, dom and cod) and a syntax for diagrams which refers to the signature.

**Comment by colltoaction** [comment]
Signatures sounds good, I will dig into that. Thank you!

I looked at the [Functors example](https://github.com/discopy/discopy/blob/main/docs/notebooks/diagrams.ipynb) and have this idea.

```yaml
- whisk: [ white, foam ]
  bake: [ foam, meringue ]
- recipe: [ whisk, bake ]

---

- recipe
- white: blanc
  foam: mousse
  meringue: meringue
- saler: blanc
  battre: [ blanc, mousse ]
  cuire: [ mousse, meringue ]
  refroidir: [ meringue, meringue ]
- whisk: [ saler, battre ]
  bake: [ cuire, refroidir ]
```
---

It is interesting that in YAML keys can be of any type, unlike JSON. There are other things that make it more powerful than JSON and worth considering.

https://yaml.org/spec/1.2.2/#chapter-3-processes-and-models
> YAML information is used in two ways: for machine processing and for human consumption. The challenge of reconciling these two perspectives is best done in three distinct translation stages: representation, serialization and presentation.

https://yaml.org/spec/1.2.2/#3211-nodes:
> In particular, keys may be arbitrary nodes, the same node may be used as the value of several key/value pairs and a mapping could even contain itself as a key or a value
